---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: centos
  labels:
    app: centos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: centos
  template:
    metadata:
      labels:
        app: centos
      annotations:
        io.katacontainers.config_path: /opt/kata/share/defaults/kata-containers/configuration-qemu-debug.toml
        #io.katacontainers.config.hypervisor.kernel: /var/lib/images/vmlinuz-4.15.0-1056-kvm
        #io.katacontainers.config.hypervisor.kernel: /var/lib/images/vmlinuz-3.10.0-1062.18.1.el7.x86_64
        io.katacontainers.config.hypervisor.kernel: /var/lib/images/vmlinuz-4.18.0-147.5.1.el8_1.x86_64
        io.katacontainers.config.hypervisor.image: /var/lib/images/kata.img
    spec:
      runtimeClassName: kata-qemu
      containers:
      - name: console
        image: quay.io/footloose/centos7
        command: [/sbin/init]
        tty: true
        securityContext:
          privileged: true
