---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: centos
  labels:
    app: centos
spec:
  replicas: 2
  selector:
    matchLabels:
      app: centos
  template:
    metadata:
      labels:
        app: centos
      annotations:
        #io.katacontainers.config_path: /opt/kata/share/defaults/kata-containers/configuration-qemu.toml
        io.katacontainers.config.hypervisor.kernel: /opt/kernels/linux-5.4.19/bzImage
    spec:
      runtimeClassName: kata-qemu
      containers:
      - name: console
        image: quay.io/footloose/centos7
        command: [/sbin/init]
        tty: true
        securityContext:
          privileged: true
