apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  region: eu-west-1
  name: test-kata-fc-2
  version: "1.15"

nodeGroups:
  - name: ng-8
    instanceType: i3.metal
    desiredCapacity: 1
    ssh: {allow: true}
    preBootstrapCommands:
      # TODO this can be a daemonset, just need to figure out how to call systemctl,
      # it also means that kubelet would have to be restarted
      - docker run -v /:/out errordeveloper/kata-installer@sha256:f8c3ff1513c979cb1f69a08fa8aa3067bbfab1efb35fcc2690410b329f904b7c

        systemctl daemon-reload
        systemctl restart containerd
        modprobe vhost_vsock

    kubeletExtraConfig:
        kubeReserved:
            cpu: "300m"
            memory: "300Mi"
            ephemeral-storage: "1Gi"
        kubeReservedCgroup: "/kube-reserved"
        systemReserved:
            cpu: "300m"
            memory: "300Mi"
            ephemeral-storage: "1Gi"
        evictionHard:
            memory.available:  "200Mi"
            nodefs.available: "10%"
        featureGates:
            DynamicKubeletConfig: true
            RotateKubeletServerCertificate: true


        serializeImagePulls: false
        tlsCipherSuites:
          - "TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256"
          - "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256"
          - "TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305"
          - "TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384"
          - "TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305"
          - "TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384"
          - "TLS_RSA_WITH_AES_256_GCM_SHA384"
          - "TLS_RSA_WITH_AES_128_GCM_SHA256"
