apiVersion: v1
kind: List
items:
- apiVersion: node.k8s.io/v1beta1
  kind: RuntimeClass
  metadata:
    name: kata-qemu
  handler: kata-qemu
- apiVersion: node.k8s.io/v1beta1
  kind: RuntimeClass
  metadata:
    name: kata-fc
  # TODO: Firecracker is not working yet, containerd needs devicemapper snaphotter for it to work
  handler: kata-fc
