apiVersion: v1
kind: List
items:
- apiVersion: apps/v1
  kind: DaemonSet
  metadata:
    name: kata-node-init
    namespace: kube-system
    labels:
      name: kata-node-init
  spec:
    selector:
      matchLabels:
        name: kata-node-init
    template:
      metadata:
        labels:
          name: kata-node-init
      spec:
        volumes:
          - name: images
            hostPath:
              path: /var/lib/images
              type: Directory
        containers:
        - name: idle
          image: k8s.gcr.io/pause:3.1
        initContainers:
        - name: extract-images
          image: errordeveloper/kata-agent:c3ba09430-ubuntu-18.04@sha256:8d56bba61851a02c1079ee0fa1681b580a2553a18aae1db2a428af2decfe2bdc
          imagePullPolicy: Always
          securityContext:
            privileged: true
          volumeMounts:
            - mountPath: /out
              name: images
