apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  region: eu-west-1
  name: kata-1
  version: "1.15"

nodeGroups:
  - name: kata-ng-1
    instanceType: i3.metal
    desiredCapacity: 1
    ssh: {allow: true}
    preBootstrapCommands:
      # TODO this can be a daemonset, just need to figure out how to call systemctl,
      # it also means that kubelet would have to be restarted
      - |
        systemctl stop kubelet

        docker run -v /:/out errordeveloper/kata-installer@sha256:40f08db23c58eb8fa9b956aad9a83887bfae2e380c08db0ea4d9e202f92f2f7b

        systemctl daemon-reload
        systemctl restart containerd
        systemctl stop docker
        systemctl disable docker

        modprobe vhost_vsock

    kubeletExtraConfig:
        cgroupDriver: systemd
        kubeReserved:
            cpu: "300m"
            memory: "300Mi"
            ephemeral-storage: "1Gi"
        kubeReservedCgroup: "/kube-reserved"
        systemReserved:
            cpu: "300m"
            memory: "300Mi"
            ephemeral-storage: "1Gi"
        evictionHard:
            memory.available:  "200Mi"
            nodefs.available: "10%"
        featureGates:
            DynamicKubeletConfig: true
            RotateKubeletServerCertificate: true


        serializeImagePulls: false
        tlsCipherSuites:
          - "TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256"
          - "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256"
          - "TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305"
          - "TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384"
          - "TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305"
          - "TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384"
          - "TLS_RSA_WITH_AES_256_GCM_SHA384"
          - "TLS_RSA_WITH_AES_128_GCM_SHA256"
