apiVersion: v1
kind: List
items:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: test-cluster-master
    labels:
      role: master
      cluster: test-cluster
  spec:
    replicas: 1
    selector:
      matchLabels:
        role: master
        cluster: test-cluster
    template:
      metadata:
        annotations:
          io.katacontainers.config_path: /opt/kata/share/defaults/kata-containers/configuration-qemu-debug.toml
          io.katacontainers.config.hypervisor.kernel: /var/lib/images/vmlinuz-5.4.19-linuxkit
          io.katacontainers.config.hypervisor.image: /var/lib/images/kata.img
        labels:
          role: master
          cluster: test-cluster
      spec:
        runtimeClassName: kata-qemu
        containers:
        - name: console
          image: errordeveloper/kubeadm:ubuntu-18.04-1.18.0
          imagePullPolicy: Always
          tty: true
          securityContext:
            privileged: true
          command:
            - /lib/systemd/systemd
            - --unit=kubeadm-init.target
          readinessProbe:
            exec:
              command:
                - systemctl
                - is-active
                - kubeadm-init.target
            initialDelaySeconds: 60
            periodSeconds: 2
            failureThreshold: 500
          env:
            - name: KUBECONFIG
              value: /etc/kubernetes/admin.conf
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: test-cluster-node
    labels:
      role: node
      cluster: test-cluster
  spec:
    replicas: 0
    selector:
      matchLabels:
        role: node
        cluster: test-cluster
    template:
      metadata:
        annotations:
          io.katacontainers.config_path: /opt/kata/share/defaults/kata-containers/configuration-qemu-debug.toml
          io.katacontainers.config.hypervisor.kernel: /var/lib/images/vmlinuz-5.4.19-linuxkit
          io.katacontainers.config.hypervisor.image: /var/lib/images/kata.img
        labels:
          role: node
          cluster: test-cluster
      spec:
        runtimeClassName: kata-qemu
        containers:
        - name: console
          image: errordeveloper/kubeadm:ubuntu-18.04-1.18.0
          imagePullPolicy: Always
          tty: true
          securityContext:
            privileged: true
          readinessProbe:
            exec:
              command:
                - systemctl
                - is-active
                - default.target
            initialDelaySeconds: 60
            periodSeconds: 10
            failureThreshold: 500
