apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: Service
  metadata:
    name: test-cluster-master
    labels:
      cluster: test-cluster
      role: master
  spec:
    ports:
    - port: 6443
      protocol: TCP
      targetPort: 6443
    selector:
      cluster: test-cluster
      role: master
    sessionAffinity: None
    type: ClusterIP
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: test-cluster-master
    labels:
      role: master
      cluster: test-cluster
  spec:
    replicas: 1
    selector:
      matchLabels:
        role: master
        cluster: test-cluster
    template:
      metadata:
        annotations:
          io.katacontainers.config_path: /opt/kata/share/defaults/kata-containers/configuration-qemu-debug.toml
          io.katacontainers.config.hypervisor.kernel: /var/lib/images/vmlinuz-5.4.19-linuxkit
          io.katacontainers.config.hypervisor.image: /var/lib/images/kata.img
        labels:
          role: master
          cluster: test-cluster
      spec:
        runtimeClassName: kata-qemu
        volumes:
          - name: images
            hostPath:
              path: /var/lib/images
              type: Directory
        containers:
        - name: console
          image: errordeveloper/kubeadm:ubuntu-18.04-1.18.0
          imagePullPolicy: Always
          tty: true
          securityContext:
            privileged: true
          command:
            - /lib/systemd/systemd
            - --unit=kubeadm.target
          readinessProbe:
            exec:
              command:
                - systemctl
                - --no-pager
                - is-active
                - kubeadm.target
            initialDelaySeconds: 180
            periodSeconds: 2
            failureThreshold: 500
          env:
            - name: KUBECONFIG
              value: /etc/kubernetes/admin.conf
          volumeMounts:
            - mountPath: /images
              name: images
          resources:
            requests:
              memory: 4Gi
              cpu: 2.1
            limits:
              memory: 4Gi
              cpu: 2.1
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: test-cluster-node
    labels:
      role: node
      cluster: test-cluster
  spec:
    replicas: 0
    selector:
      matchLabels:
        role: node
        cluster: test-cluster
    template:
      metadata:
        annotations:
          io.katacontainers.config_path: /opt/kata/share/defaults/kata-containers/configuration-qemu-debug.toml
          io.katacontainers.config.hypervisor.kernel: /var/lib/images/vmlinuz-5.4.19-linuxkit
          io.katacontainers.config.hypervisor.image: /var/lib/images/kata.img
        labels:
          role: node
          cluster: test-cluster
      spec:
        runtimeClassName: kata-qemu
        containers:
        - name: console
          image: errordeveloper/kubeadm:ubuntu-18.04-1.18.0
          imagePullPolicy: Always
          tty: true
          securityContext:
            privileged: true
          readinessProbe:
            exec:
              command:
                - systemctl
                - --no-pager
                - is-active
                - default.target
            initialDelaySeconds: 60
            periodSeconds: 10
            failureThreshold: 500
