apiVersion: v1
kind: List
items:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: test-cluter-master
    labels:
      role: master
  spec:
    replicas: 1
    selector:
      matchLabels:
        role: master
    template:
      metadata:
        labels:
          role: master
      spec:
        runtimeClassName: kata-qemu
        containers:
        - name: console
          image: errordeveloper/kubeadm:ubuntu-18.04-1.18.0
          imagePullPolicy: Always
          command: [/sbin/init]
          tty: true
          securityContext:
            privileged: true
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: test-cluster-node
    labels:
      role: node
  spec:
    replicas: 3
    selector:
      matchLabels:
        role: node
    template:
      metadata:
        labels:
          role: node
      spec:
        runtimeClassName: kata-qemu
        containers:
        - name: console
          image: errordeveloper/kubeadm:ubuntu-18.04-1.18.0
          imagePullPolicy: Always
          command: [/sbin/init]
          tty: true
          securityContext:
            privileged: true
