apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: Service
  metadata:
    name: test-cluster-master
    labels:
      cluster: test-cluster
      role: master
  spec:
    ports:
    - port: 6443
      protocol: TCP
      targetPort: 6443
    selector:
      cluster: test-cluster
      role: master
    sessionAffinity: None
    type: ClusterIP

- apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: test-cluster-master
    labels:
      role: master
      cluster: test-cluster
  automountServiceAccountToken: false

- apiVersion: v1
  kind: Secret
  metadata:
    name: test-cluster-kubeconfig
    labels:
      cluster: test-cluster

- apiVersion: v1
  kind: Secret
  metadata:
    name: test-cluster-join-token
    labels:
      cluster: test-cluster

- apiVersion: rbac.authorization.k8s.io/v1
  kind: Role
  metadata:
    name: test-cluster-master
  rules:
  - apiGroups:
    - ""
    resources:
    - secrets
    verbs:
    - get
    #- watch
    #- update
    - patch
    resourceNames:
    - test-cluster-kubeconfig
    - test-cluster-join-token

- apiVersion: rbac.authorization.k8s.io/v1
  kind: RoleBinding
  metadata:
    name: test-cluster-master
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: test-cluster-master
  subjects:
  - kind: ServiceAccount
    name: test-cluster-master

- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: test-cluster-master
    labels:
      role: master
      cluster: test-cluster
  spec:
    replicas: 1
    selector:
      matchLabels:
        role: master
        cluster: test-cluster
    template:
      metadata:
        annotations:
          io.katacontainers.config_path: /opt/kata/share/defaults/kata-containers/configuration-qemu-debug.toml
          io.katacontainers.config.hypervisor.kernel: /var/lib/images/kernel/linuxkit/vmlinuz-5.4.19-linuxkit
          io.katacontainers.config.hypervisor.image: /var/lib/images/vm/kata-agent-ubuntu.img
          io.katacontainers.config.hypervisor.default_vcpus: "2"
          # kata cannot set VM memory correctly with linuxit kernel - TODO check if CONFIG_MEMORY_HOTPLUG is set
          io.katacontainers.config.hypervisor.default_memory: "4096"
        labels:
          role: master
          cluster: test-cluster
      spec:
        runtimeClassName: kata-qemu
        serviceAccountName: test-cluster-master
        volumes:
          - name: images
            hostPath:
              path: /var/lib/images
              type: Directory
          - name: bpf-maps
            hostPath:
              path: /sys/fs/bpf
              type: Directory
          # the following volumes are mostly required in non-kata setting, but should also work with kata
          - name: proc
            hostPath:
              path: /proc
              type: Directory
          - hostPath:
              # TODO: stop actually including modules in the image, these could live in kata VM, or better on the
              # host and managed by node init ds, the kata VM and kernel lifecycles are bound anyway, so either
              # way is the same, except that kata VM image might be better to keep small
              path: /lib/modules
              type: Directory
            name: lib-modules
          - hostPath:
              path: /run/xtables.lock
              type: FileOrCreate
            name: xtables-lock
          # custom service account token mount, this is needed due to systemd shaddowing /run/secrets
          - projected:
              sources:
              - serviceAccountToken:
                  path: token
            name: parent-management-cluster-service-account-token
          # pass cluster name
          - downwardAPI:
              items:
              - path: labels
                fieldRef:
                  fieldPath: metadata.labels
            name: metadata

        # TODO add initContainers to wait for /var/images to have the right files, or at least some file
        containers:
        - name: console
          image: errordeveloper/kubeadm:ubuntu-18.04-1.18.0@sha256:60ebabdaafcb912bc8a73c3bbba156a69956f177d277dc14b78a0faeaf098004
          imagePullPolicy: Always
          tty: true
          securityContext:
            privileged: true
          command:
            - /lib/systemd/systemd
            - --unit=kubeadm.target
          readinessProbe:
            exec:
              command:
                - /usr/bin/is-master-ready.sh
            initialDelaySeconds: 30
            periodSeconds: 2
            failureThreshold: 500
            successThreshold: 5
          env:
            - name: KUBECONFIG
              value: /etc/kubernetes/admin.conf
          volumeMounts:
            - mountPath: /images
              name: images
            - mountPath: /sys/fs/bpf
              name: bpf-maps
              mountPropagation: Bidirectional # required due to nesting, so that cilium pod can use
            - mountPath: /lib/modules
              name: lib-modules
              readOnly: true
            - mountPath: /run/xtables.lock
              name: xtables-lock
            - mountPath: /etc/parent-management-cluster/secrets
              name: parent-management-cluster-service-account-token
            - mountPath: /etc/kubeadm/metadata
              name: metadata
          #resources:
          #  requests:
          #    memory: 4Gi
          #    cpu: 2.1
          #  limits:
          #    memory: 4Gi
          #    cpu: 2.1

- apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: test-cluster-node
    labels:
      role: node
      cluster: test-cluster
  automountServiceAccountToken: false

- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: test-cluster-node
    labels:
      role: node
      cluster: test-cluster
  spec:
    replicas: 1
    selector:
      matchLabels:
        role: node
        cluster: test-cluster
    template:
      metadata:
        annotations:
          io.katacontainers.config_path: /opt/kata/share/defaults/kata-containers/configuration-qemu-debug.toml
          io.katacontainers.config.hypervisor.kernel: /var/lib/images/kernel/linuxkit/vmlinuz-5.4.19-linuxkit
          io.katacontainers.config.hypervisor.image: /var/lib/images/vm/kata-agent-ubuntu.img
          io.katacontainers.config.hypervisor.default_vcpus: "2"
          # kata cannot set VM memory correctly with linuxit kernel - TODO check if CONFIG_MEMORY_HOTPLUG is set
          io.katacontainers.config.hypervisor.default_memory: "4096"
        labels:
          role: node
          cluster: test-cluster
      spec:
        runtimeClassName: kata-qemu
        serviceAccountName: test-cluster-node
        volumes:
          - name: images
            hostPath:
              path: /var/lib/images
              type: Directory
          - name: bpf-maps
            hostPath:
              path: /sys/fs/bpf
              type: Directory
          # the following volumes are mostly required in non-kata setting, but should also work with kata
          - hostPath:
              # TODO: stop actually including modules in the image, these could live in kata VM, or better on the
              # host and managed by node init ds, the kata VM and kernel lifecycles are bound anyway, so either
              # way is the same, except that kata VM image might be better to keep small
              # TODO: qn - does kata mount 
              path: /lib/modules
              type: Directory
            name: lib-modules
          - hostPath:
              path: /run/xtables.lock
              type: FileOrCreate
            name: xtables-lock
          # custom service account token mount, this is needed due to systemd shaddowing /run/secrets
          - projected:
              sources:
              - serviceAccountToken:
                  path: token
            name: parent-management-cluster-service-account-token
          # pass cluster name
          - downwardAPI:
              items:
              - path: labels
                fieldRef:
                  fieldPath: metadata.labels
            name: metadata
          # mount join token
          - projected:
              sources:
              - secret:
                  name: test-cluster-join-token
                  optional: false
            name: join-secret
        containers:
        - name: console
          image: errordeveloper/kubeadm:ubuntu-18.04-1.18.0@sha256:60ebabdaafcb912bc8a73c3bbba156a69956f177d277dc14b78a0faeaf098004
          imagePullPolicy: Always
          tty: true
          securityContext:
            privileged: true
          readinessProbe:
            exec:
              command:
                - systemctl
                - --no-pager
                - is-active
                - multi-user.target
            initialDelaySeconds: 120
            periodSeconds: 2
            failureThreshold: 500
          volumeMounts:
            - mountPath: /images
              name: images
            - mountPath: /sys/fs/bpf
              name: bpf-maps
              mountPropagation: Bidirectional # required due to nesting, so that cilium pod can use
            - mountPath: /lib/modules
              name: lib-modules
              readOnly: true
            - mountPath: /run/xtables.lock
              name: xtables-lock
            - mountPath: /etc/parent-management-cluster/secrets
              name: parent-management-cluster-service-account-token
            - mountPath: /etc/kubeadm/metadata
              name: metadata
            - mountPath: /etc/kubeadm/secrets
              name: join-secret
